#!/usr/bin/env bash
# sets up a new 404 error page
sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" > index.html
sudo mv index.html /var/www/html

# Performing a "moved permanently redirection" (301)
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/besthor permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

#Testing error page
sudo nginx -t

#restart nginx
sudo service nginx restart
